version: 0.2
        
phases:
  install:
    on-failure: ABORT
    commands:
      - npm install -g typescript
      - npm install -g ts-node
      - npm install -g aws-cdk
      - npm install
      - cdk --version
  build:
    on-failure: ABORT
    commands:
      - ls
      - cdk synth
artifacts:
  files:
    - cdk.out/*
  discard-paths: no
  enable-symlinks: yes