version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - pip install --upgrade pip
      - npm install --location=global typescript
      - npm install --location=global ts-node
      - npm install --location=global aws-cdk
      - cdk --version
  build:
    commands:
      - pip install -r requirements.txt
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_session_token $AWS_SESSION_TOKEN
      - aws configure set region "us-east-1"
      - yes "" | aws configure
      - export CDK_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - |
        cdk bootstrap \
        --profile default \
        --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
      # - |
      #   cdk deploy \
      #   --profile default \
      #   --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
      #   --require-approval never --force true
      - |
        if [ "${cdk_destroy}" = true ] ; then
          cdk destroy \
          --profile default \
          --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
          --require-approval never --force true
        else
          cdk deploy \
          --profile default \
          --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess \
          --require-approval never --force true
        fi


  