version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
  build:
    commands:
      # - python3 -m venv .venv
      # - source .venv/bin/activate
      - pip install -r requirements.txt
      - cdk bootstrap
      - cdk deploy